# Generated by Django 4.2.7 on 2023-11-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'verbose_name_plural': 'BlogArticles'},
        ),
    ]
